name: STRIDE-GPT Security Analysis

on:
  workflow_dispatch:  # Manual trigger
  pull_request:       # Auto-trigger on PRs
    types: [opened, synchronize]

jobs:
  security-analysis:
    runs-on: ubuntu-latest
    name: STRIDE Threat Modeling

    steps:
    - name: Run STRIDE-GPT Analysis
      uses: mrwadams/stridegpt-action@main
      with:
        stride-api-key: ${{ secrets.STRIDE_API_KEY }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
