name: Security Analysis on Comment

on:
  issue_comment:
    types: [created]

jobs:
  stride-analysis:
    # Run on both issue and PR comments that mention @stride-gpt
    if: contains(github.event.comment.body, '@stride-gpt')
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
      - name: Run STRIDE-GPT Analysis
        uses: mrwadams/stridegpt-action@main
        with:
          stride-api-key: ${{ secrets.STRIDE_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          trigger-mode: comment
