name: STRIDE-GPT Security Analysis

on:
  workflow_dispatch:

jobs:
  security-analysis:
    runs-on: ubuntu-latest
    name: STRIDE Threat Modeling

    steps:
    - name: Debug container
      uses: mrwadams/stridegpt-action@main
      with:
        stride-api-key: ${{ secrets.STRIDE_API_KEY }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
